### ISSUE TITLE
Difference from Kijai CogVideoX_Wrapper? 

### ISSUE THREAD

**Issue by Ainaemaet** [florestefano1975/ComfyUI-CogVideoX#1]
Hello, I'm just wondering if you can please tell me if this project does anything different than Kijai's CogVideoX Wrapper one found here https://github.com/kijai/ComfyUI-CogVideoXWrapper? 

Not a criticism, just curious what differences there may be - and what you have planned for the future of your CogVideoX custom nodes that make it stand out?

**Comment by florestefano1975** [comment]
My custom node is completely in the experimental stage. I am trying to overcome with a series of automations the 49-frame limit. I have released an update that allows concatenating multiple generations, where those following the first one resume from the last frame of the previous one. In addition, I included a frame interpolation system that allows for increased smoothness and length of the final video. With these arrangements, I was able to create fairly smooth and consistent 6-second videos.

**Comment by florestefano1975** [comment]
Example of video generated: https://www.threads.net/@stefano.flore.75/post/DBMn86DuVoq

**Comment by Ainaemaet** [comment]
> My custom node is completely in the experimental stage. I am trying to overcome with a series of automations the 49-frame limit. I have released an update that allows concatenating multiple generations, where those following the first one resume from the last frame of the previous one. In addition, I included a frame interpolation system that allows for increased smoothness and length of the final video. With these arrangements, I was able to create fairly smooth and consistent 6-second videos.

Thanks for the explanation and example, that actually looks really great - good job. :) 

Really nice to see other people working towards fleshing things out for CogVideoX!

**Comment by ShmuelRonen** [comment]
I cant find your nodes in search... although it in custom_nodes list ???

Do you have any workflow that I can try?

**Comment by florestefano1975** [comment]
> I cant find your nodes in search... although it in custom_nodes list ???
> 
> Do you have any workflow that I can try?

I have submitted a request for inclusion on the Manager's list. Alternatively, you can install it manually.

**Comment by ShmuelRonen** [comment]
> > I cant find your nodes in search... although it in custom_nodes list ???
> > Do you have any workflow that I can try?
> 
> I have submitted a request for inclusion on the Manager's list. Alternatively, you can install it manually.

I change your code to this and it solve the problem for me:

 NODE_CLASS_MAPPINGS = {
    "CogVideoX Image-2-Video": CogVideoXImageToVideoNode,
    "CogVideoX Image-2-Video Extended": CogVideoXImageToVideoNodeExtended,
    "CogVideoX Save Video": SaveVideoNode,
}


![Screenshot 2024-10-18 142949](https://github.com/user-attachments/assets/391249fd-b240-4180-8219-02182537be58)

**Comment by ShmuelRonen** [comment]
With No emoji!!!
